version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/git-involved
    steps:
      - type: checkout
      - type: shell
        name: build
        command: docker-compose build

  start:
    steps:
      - name: start
        command: docker-compose up -d

  test:
    steps:
      - name: elm tests
        command: yarn test

