version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/git-involved
    steps:
      - checkout
      - run:
          name: build images
          command: docker-compose build
      - run:
          name: start the containers
          command: docker-compose up -d
      - run:
          name: elm tests
          command: docker-compose exec node npm run test
      - run:
          name: push the images
          command: |
            docker tag gitinvolvedelm_node:latest happysalada/gitinvolved_node:latest
            docker tag gitinvolvedelm_node:latest happysalada/gitinvolved_nginx:latest
            docker push happysalada/gitinvolved_node:latest
            docker push happysalada/gitinvolved_nginx:latest
