version: 2
executorType: machine
stages:
  build:
    working_directory: ~/git-involved
    steps:
      - checkout
      - run:
          name: build images
          command: docker-compose build
      - run:
          name: elm tests
          command: npm run test
