version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/git-involved
    steps:
      - checkout
      - run:
          name: build images
          command: docker-compose build
      - run:
          name: start the containers
          command: docker-compose up
      - run:
          name: elm tests
          command: docker-compose exec node npm run test
