version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/git-involved
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: elm tests
          command: npm run test
